

name: Build ESP32 Firmware

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup ESP-IDF
        uses: espressif/setup-esp-idf@v1
        with:
          esp-idf-version: v5.1
          esp-idf-target: esp32

      - name: Compilar
        run: idf.py build

      - name: Salvar firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/*.bin
